version: '3.8'

services:
  user-service:
    image: user-service
    ports:
      - "8080:8080"
    env_file:
      - userenv.list

  gateway-service:
    image: gateway-service
    ports:
      - "5001:5001"
    env_file:
      - gatewayenv.list
    depends_on:
      - user-service
