apiVersion: v1
kind: ConfigMap
metadata:
  name: subscription-config
data:
  NEO4J_URI: bolt://neo4j-service:7687
  NEO4J_USERNAME: neo4j
  NEO4J_PASSWORD: cmuxpassword
  SPRING_NEO4J_URI: bolt://neo4j-service:7687
  SPRING_NEO4J_AUTHENTICATION_USERNAME: neo4j
  SPRING_NEO4J_AUTHENTICATION_PASSWORD: cmuxpassword
  SPRING_DATA_NEO4J_DATABASE: neo4j
  SERVER_PORT: "8082"
