version: '3'

services:
  mysql:
    image: mysql:8.1.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: zhangzcx1999
      MYSQL_DATABASE: myPostServiceDB
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql 

  postservice:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: postservice
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/myPostServiceDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: zhangzcx1999
    volumes:
      - .:/app
    restart: always
    depends_on:
      - mysql

volumes:
  mysql-data:
