version: '3'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: frontend-container2
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
