apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user-container
          image: hanqid/cmux-user
          imagePullPolicy: Always
          ports:
            - containerPort: 5002
          envFrom:
            - configMapRef:
                name: user-service-env
